/**
 * @jest-environment node
 */
import fs from 'fs';
import path from 'path';
import { BIN_COUNT, binOf, binRanges, quantileThresholds } from '@/lib/choropleth';
import { COUNTIES, COUNTY_BY_CODE } from '@/lib/regions';
import type { CountyShapes } from '@/hooks/useCountyGeometry';

const ASSET = path.join(process.cwd(), 'public/geo/swedish-counties.json');
const shapes: CountyShapes = JSON.parse(fs.readFileSync(ASSET, 'utf8'));

/**
 * The prebuilt geometry.
 *
 * These paths are generated by `npm run build:geo` and committed, so nothing
 * regenerates them on a normal build and nothing here can catch a bad
 * regeneration except a test that looks at what was committed.
 */
describe('the county outlines that ship', () => {
  it('carries all twenty-one counties, keyed on the official codes', () => {
    expect(shapes.counties).toHaveLength(21);

    const codes = shapes.counties.map((c) => c.lanskod);
    expect(new Set(codes).size).toBe(21);
    // Every shape must find a county, or the map draws a hole where one is.
    for (const code of codes) expect(COUNTY_BY_CODE[code]).toBeDefined();
  });

  it('covers every county the breakdown can produce', () => {
    const drawn = new Set(shapes.counties.map((c) => COUNTY_BY_CODE[c.lanskod]));
    expect([...COUNTIES].filter((county) => !drawn.has(county))).toEqual([]);
  });

  /*
   * The shape of the country, as a number.
   *
   * d3-geo decides which side of a ring is inside from its winding order, and
   * wants exterior rings clockwise — the opposite of RFC 7946, which is what
   * the source file carried. Wound the wrong way every county reads as the
   * whole globe with a county-shaped hole in it, `fitWidth` dutifully fits the
   * globe, and the output is a Sweden squashed into a perfect square. Nothing
   * throws and the file looks entirely normal.
   *
   * Sweden is about 1,572 km tall and 499 km wide. On a Mercator projection at
   * this latitude the ratio comes out near 2.3; a square is 1.0.
   */
  it('is the shape of Sweden and not a square', () => {
    const ratio = shapes.height / shapes.width;
    expect(ratio).toBeGreaterThan(1.8);
    expect(ratio).toBeLessThan(2.8);
  });

  it('draws every county as a closed path inside the viewbox', () => {
    for (const county of shapes.counties) {
      expect(county.d.startsWith('M')).toBe(true);
      expect(county.d.endsWith('Z')).toBe(true);

      const numbers = county.d.match(/-?\d+(\.\d+)?/g) ?? [];
      expect(numbers.length).toBeGreaterThan(10);
      for (let i = 0; i < numbers.length; i += 2) {
        const x = Number(numbers[i]);
        const y = Number(numbers[i + 1]);
        expect(x).toBeGreaterThanOrEqual(0);
        expect(x).toBeLessThanOrEqual(shapes.width);
        expect(y).toBeGreaterThanOrEqual(0);
        expect(y).toBeLessThanOrEqual(shapes.height);
      }
    }
  });

  // Gotland is an island: if the projection or the winding were wrong it would
  // be the first thing to end up somewhere else entirely.
  it('puts north up, east right, and Gotland in the Baltic', () => {
    const box = (code: string) => {
      const numbers = (shapes.counties.find((c) => c.lanskod === code)?.d.match(/-?\d+(\.\d+)?/g) ?? [])
        .map(Number);
      const xs = numbers.filter((_, i) => i % 2 === 0);
      const ys = numbers.filter((_, i) => i % 2 === 1);
      return { cx: (Math.min(...xs) + Math.max(...xs)) / 2, cy: (Math.min(...ys) + Math.max(...ys)) / 2 };
    };

    const norrbotten = box('25');
    const skane = box('12');
    const gotland = box('09');
    const vastraGotaland = box('14');

    expect(norrbotten.cy).toBeLessThan(skane.cy);
    expect(norrbotten.cx).toBeGreaterThan(skane.cx);
    // Gotland sits east of the mainland's west coast and south of the middle.
    expect(gotland.cx).toBeGreaterThan(vastraGotaland.cx);
    expect(gotland.cy).toBeGreaterThan(shapes.height / 2);
  });

  // Fetched by every reader who opens the statistics view, and geometry is the
  // easiest thing in a repository to replace with a 4 MB version by accident.
  it('stays small enough to fetch without thinking about it', () => {
    expect(fs.statSync(ASSET).size).toBeLessThan(40_000);
  });
});

describe('sorting counties into shades', () => {
  // Notices follow population: Stockholm is about a fifth of the country on its
  // own and most counties sit under three percent. Cut into equal-width bands,
  // twenty of twenty-one land in the palest one and the map says nothing.
  const skewed = [0.23, 0.16, 0.14, 0.045, 0.042, 0.038, 0.031, 0.031, 0.028, 0.027, 0.027,
    0.027, 0.027, 0.027, 0.017, 0.016, 0.016, 0.016, 0.015, 0.015, 0.015];

  it('spreads a skewed distribution across every shade', () => {
    const thresholds = quantileThresholds(skewed);
    const used = new Set(skewed.map((v) => binOf(v, thresholds)));

    expect(used.size).toBe(BIN_COUNT);
  });

  it('puts roughly a quarter of the counties in each shade', () => {
    const thresholds = quantileThresholds(skewed);
    const counts = [0, 0, 0, 0];
    for (const v of skewed) counts[binOf(v, thresholds)]++;

    for (const count of counts) {
      expect(count).toBeGreaterThanOrEqual(3);
      expect(count).toBeLessThanOrEqual(9);
    }
    expect(counts.reduce((a, b) => a + b, 0)).toBe(skewed.length);
  });

  it('gives the largest county the darkest shade and the smallest the palest', () => {
    const thresholds = quantileThresholds(skewed);

    expect(binOf(0.23, thresholds)).toBe(BIN_COUNT - 1);
    expect(binOf(0.015, thresholds)).toBe(0);
  });

  // A cut has to have something below it. Landing on a run of equal values, or
  // on the smallest value of all, produces a boundary nothing falls under: an
  // empty palest bin, and a legend band belonging to no counties.
  it('never cuts where nothing falls below the cut', () => {
    const tied = [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.2];
    const thresholds = quantileThresholds(tied);

    expect(new Set(thresholds).size).toBe(thresholds.length);
    expect(binOf(0.05, thresholds)).toBe(0);
    expect(binOf(0.2, thresholds)).toBeGreaterThan(0);
    // Every bin the thresholds imply has at least one county in it.
    const used = new Set(tied.map((v) => binOf(v, thresholds)));
    expect(used.size).toBe(thresholds.length + 1);
  });

  it('survives having nothing to bin', () => {
    expect(quantileThresholds([])).toEqual([]);
    expect(binOf(0.5, [])).toBe(0);
    expect(binRanges([], [])).toEqual([{ from: 0, to: 0 }]);
  });

  it('labels each band from the lowest value to the highest', () => {
    const thresholds = quantileThresholds(skewed);
    const ranges = binRanges(skewed, thresholds);

    expect(ranges).toHaveLength(BIN_COUNT);
    expect(ranges[0].from).toBeCloseTo(0.015);
    expect(ranges[ranges.length - 1].to).toBeCloseTo(0.23);
    // Contiguous: no gap between one band's top and the next one's bottom.
    for (let i = 1; i < ranges.length; i++) {
      expect(ranges[i].from).toBeCloseTo(ranges[i - 1].to);
    }
  });
});
