/**
 * The centre of every Swedish municipality, as a lookup table.
 *
 *   npm run build:geo
 *
 * Why this exists: polisen.se files a notice with `location.name` set to a
 * county and `location.gps` set to that county's centre. A month of national
 * notices therefore lands on twenty-one coordinates, and the map draws a
 * country with twenty-one dots on it. The notice's own title is finer — "16
 * juli 08:53, Trafikolycka, Ljungby" — and the app already parses the
 * municipality out of it for the feed rows. This table is what lets the map use
 * it too.
 *
 * Centroids come from the same source as the county outlines: okfse's
 * municipality file carries a `geo_point_2d` per kommun, computed from the
 * polygon. Brottsplatskartan's own coordinates were produced the same way,
 * which is why the archive already plots at municipality level and the live
 * feed does not.
 *
 * Written as a TypeScript module rather than JSON so the name list is typed and
 * so nothing has to resolve a file path at runtime.
 */
import fs from 'fs';
import path from 'path';
import type { FeatureCollection, Geometry } from 'geojson';

interface MunicipalityProperties {
  kom_namn: string;
  lan_code: string;
  id: string;
  /** [lat, lng], which is the order this source uses. */
  geo_point_2d: [number, number];
}

const SOURCE = path.join(process.cwd(), 'scripts/geo/swedish-municipalities.source.geojson');
const OUTPUT = path.join(process.cwd(), 'src/lib/municipalityCentroids.ts');

/** Sweden's bounding box, give or take. A centroid outside it is a bad row. */
const BOUNDS = { minLat: 55.0, maxLat: 69.5, minLng: 10.5, maxLng: 24.5 };

function main(): void {
  const geo = JSON.parse(fs.readFileSync(SOURCE, 'utf8')) as FeatureCollection<
    Geometry,
    MunicipalityProperties
  >;

  const rows = geo.features
    .map((feature) => {
      const [lat, lng] = feature.properties.geo_point_2d;
      return { name: feature.properties.kom_namn, lat, lng };
    })
    .sort((a, b) => a.name.localeCompare(b.name, 'sv'));

  if (rows.length !== 290) {
    throw new Error(`expected 290 municipalities, got ${rows.length}`);
  }

  for (const row of rows) {
    if (
      !Number.isFinite(row.lat) ||
      !Number.isFinite(row.lng) ||
      row.lat < BOUNDS.minLat ||
      row.lat > BOUNDS.maxLat ||
      row.lng < BOUNDS.minLng ||
      row.lng > BOUNDS.maxLng
    ) {
      // Catches a lat/lng swap, which is the classic failure here and puts every
      // Swedish municipality somewhere in Somalia.
      throw new Error(`${row.name} is at ${row.lat},${row.lng}, which is not in Sweden`);
    }
  }

  // Keys are emitted already lowercased and single-spaced, which is the shape
  // the lookup normalises to. Doing it here rather than in a .map() at module
  // load keeps the generated file a plain literal: no work at import time, and
  // nothing for a type checker to infer its way through.
  const entries = rows
    .map((row) => {
      const key = row.name.toLowerCase().replace(/\s+/g, ' ').replace(/'/g, "\\'");
      return `  ['${key}', [${row.lat.toFixed(4)}, ${row.lng.toFixed(4)}]], // ${row.name}`;
    })
    .join('\n');

  const file = `// Generated by scripts/build-municipality-centroids.ts — do not edit.
// Run \`npm run build:geo\` to regenerate.
//
// The centre of each of Sweden's 290 municipalities, [lat, lng], from okfse's
// municipality polygons. Used to position a notice whose location field names
// only a county but whose title names the municipality.
//
// Keys are lowercased and single-spaced; look up with the same normalisation.

export const MUNICIPALITY_CENTROIDS: ReadonlyMap<string, readonly [number, number]> = new Map([
${entries}
]);
`;

  fs.writeFileSync(OUTPUT, file);
  console.log(`${rows.length} municipality centroids -> ${(fs.statSync(OUTPUT).size / 1024).toFixed(1)} kB`);
}

main();
